### ISSUE TITLE
Min SDK Level?

### ISSUE THREAD

**Issue by simophin** [requery/requery#105]
Hi there,
I'm wondering why this project's min SDK is at 15 instead of commonly used 14? This is the only hurdle for this library to be used in our project.

Thanks.

**Comment by npurushe** [comment]
Hmm I don't think 14 is commonly used. If you check [Google's dashboard metrics](http://developer.android.com/intl/es/about/dashboards/index.html) only 15 represents ICS. Basically there shouldn't be any devices still out there that are at API level 14 as explained in this [Stackoverflow post](http://stackoverflow.com/questions/13544696/android-development-api-14-vs-api-15). That's why if you create a new project in Android Studio it defaults to 15 not 14. If you have specific devices at API level 14 let me know possibly it can be adjusted down but probably not a good idea to change it unless it's really needed, since dependencies have to be changed as well.

**Comment by npurushe** [comment]
Since its a small change that doesn't effect anything went ahead and made it

**Comment by simophin** [comment]
You are right, API 14 isn't necessarily the most commonly used min SDK, I just needed to know if there's particular reason to target API 15. Because API 14 is actually the start of most significant change since Android 2.x, and also we had agreement with our clients that the applications will target Android 4.0, it's kind of hard to explain to the clients that we can only do from API 15.

Though I do appreciate all your effort, it's such a great framework.

**Comment by npurushe** [comment]
Sure thanks. Try 1.0.0-beta16 this version has the updated android library with min sdk 14
