### ISSUE TITLE
requery-android: How to run transaction with Rx

### ISSUE THREAD

**Issue by ZeDzislaw** [requery/requery#106]
I want to run update on two models of same type using SingleEntityStore<Persistable> converting .update() to .toObservable() with transaction. Could You give me any reference, how to do this?
Thanks.

**Comment by npurushe** [comment]
Currently this isn't supported because of the potential asynchronous nature of those calls and transactions are depending on some thread local state to work. At the moment you have to use `runInTransaction` from BlockingEntityStore to do this. 
```java
BlockingEntityStore store = data.toBlocking();
store.runInTransaction(new Callable<Void>() {
  // your update calls against the blocking API
});
```
You can create an Rx observable or Single from that block of code. But will provide an improved api to create a bunch of Operations and create a Observable of them which can executed in a transaction when subscribed to.
