### ISSUE TITLE
Incorrect inheritance if basic class in separate library

### ISSUE THREAD

**Issue by vmitiaev** [requery/requery#112]
If the basic class (Entity) with the annotation of Superclass to be in separate library, then the result generated derived class (Pass) doesn't inherit property of a basic class. If the basic (Entity) and derived class (AbstractPass) are in one libraries or the application, then all - ok.

`@Superclass`
`public abstract class Entity {`
    
    public BaseEntity() {
    }

    @Key @Generated
    protected int id;

    @Column(name = "creation_date", nullable = false)
    protected long creationDate;

    @Column(name = "last_modified_date", nullable = false)
    protected long lastModifiedDate;

    @Column(name = "deleted", nullable = false)
    @Naming(getter = "isDeleted")
    protected boolean deleted;
`}`

`@Entity`
`@Table(name = "pass")`
`public abstract class AbstractPass extends BaseEntity {`

    @Column(name = "name", nullable = false)
    protected int name;

    @Column(name = "number", nullable = false)
    protected String number;

    @Column(name = "type", nullable = false)
    protected int type;

    @Column(name = "state", nullable = false)
    protected int state;
`}`

**Comment by npurushe** [comment]
Hi yes the annotation processor is run separately two different times in this case so it's not possible to know about any processing done on the library containing the base class. One possibility may be to check the type hierarchy of the entity class and try to generated the superclass data that way, but there could be some issues doing it that way since the processor is run differently possibly without access to source code containing the base class (so things like arg names maybe missing).
