### ISSUE TITLE
Parcelable issue for relationship entity

### ISSUE THREAD

**Issue by tsunamilx** [requery/requery#123]
Parcelable seems not working for relationship entity.

Before I start an activity, the entity fields are good:
![1](https://cloud.githubusercontent.com/assets/6290337/14975064/62eb0a9c-1130-11e6-84e5-1eaf11f0415b.jpg)

Then I check in the received activity, all relationship fields are null:
![2](https://cloud.githubusercontent.com/assets/6290337/14975083/7f2d2e6a-1130-11e6-9474-5088ef4a9a66.jpg)

Did I miss something? Is this related to lazy loading?

**Comment by npurushe** [comment]
Hi parceling relational data is not supported, only the direct fields of the entity. This is because the relational graph of objects can have cycles and refer back to the same object which is not supported by Parcelable. In general it doesn't make sense to do that inside your own process, instead include a unique id for the object in the bundle and retrieve it using [findByKey](http://requery.github.io/javadoc/io/requery/EntityStore.html#findByKey-java.lang.Class-K-) this is more efficient and when combined with entity caching (which is default enabled) preserves the in memory state of the object.

**Comment by npurushe** [comment]
You can find an example of this [here](https://github.com/requery/requery/blob/master/requery-android/example/src/main/java/io/requery/android/example/app/PersonEditActivity.java#L60)

**Comment by tsunamilx** [comment]
OK, good to know. Thanks a lot!

**Comment by npurushe** [comment]
Sure :)
