### ISSUE TITLE
requery-android sub project missed dependencies on jcenter repo

### ISSUE THREAD

**Issue by cocia** [requery/requery#141]
My project depends on:
```gradle
    compile 'io.requery:requery:1.0.0-beta18'
    compile 'io.requery:requery-android:1.0.0-beta18' // for android
    apt 'io.requery:requery-processor:1.0.0-beta18'   // use an APT plugin
```
When I try to use "SqlCipherDatabaseSource", got compile error:can not find "net.sqlcipher.database.SQLiteDatabase".

I added dependency to gradle like this:
```gradle
    compile 'io.requery:requery:1.0.0-beta18'
    compile 'io.requery:requery-android:1.0.0-beta18' // for android
    compile 'net.zetetic:android-database-sqlcipher:3.4.0' //for sql cipher
    apt 'io.requery:requery-processor:1.0.0-beta18'   // use an APT plugin
```
It works.
I found this pom doesn't have any dependencies 
https://jcenter.bintray.com/io/requery/requery-android/1.0.0-beta18/:requery-android-1.0.0-beta18.pom
 So I supposed this is a missed configuration.

How do you think?

**Comment by npurushe** [comment]
This is mostly intentional since SQLCipher is an optional dependency it's not required to use the android module. The dependencies can be included in the pom with the maven provided scope but there was an issue with that at the time the project was created maybe it is fixed with the latest gradle version. 

However that would not change the end result as you would still need to specify the SQLCipher dependency in your gradle configuration with the compile scope to include it (as you did in your example).

**Comment by cocia** [comment]
Got your idea.
I suggest to include this in chapter wiki/Android/SQLCipher  for end user.

**Comment by npurushe** [comment]
Sure it will be updated with that information

**Comment by npurushe** [comment]
Updated the wiki with this info
