### ISSUE TITLE
AutoValue ForeignKey Android example

### ISSUE THREAD

**Issue by adauvalter** [requery/requery#146]
Is there some example, how to implement on Android relationships with ```Autovalue``` without ```@JoinColumn``` annotation?

**Comment by npurushe** [comment]
Hi this would be similar just the annotations would be slightly different (using the requery annotations instead of the JPA ones). Example:

```java
@Entity
@AutoValue
public abstract class Phone {

    public static Phone create(int id, String phoneNumber, boolean normalized, int ownerId) {
        return new AutoValue_Phone(id, phoneNumber, normalized, ownerId);
    }

    @Key @Generated
    public abstract int getId();
    public abstract String getPhoneNumber();
    public abstract boolean isNormalized();

    @ForeignKey(references = Person.class)
    public abstract int getOwnerId();
}
```

Hope that helps

**Comment by adauvalter** [comment]
Should be any reference defined from ```Person.class``` to ```Phone.class```?

**Comment by npurushe** [comment]
In this case no it's not needed as in that example there is a many-to-one relationship effectively between phone numbers and the person it belongs to.

**Comment by adauvalter** [comment]
Nice, thank you!

**Comment by npurushe** [comment]
Sure this was added under the section [Immutable Types](https://github.com/requery/requery/wiki/Immutable-types)

**Comment by aegis123** [comment]
how would this work with one to many or many to many?

like person has multiple phone numbers? Or with something like a User object and Message object. Message object has both a sender and a list of receivers and the User object has a list of send Messages and a list of received Messages.

```
@Entity
@AutoValue
public abstract class Person {
    @Key @Generated
    public abstract int getId();

    public abstract String getName();
    public abstract Date getBirthday();
    public abstract int getAge();
    public abstract List<Phone> phoneNumbers();
}
```

**Comment by RoryKelly** [comment]
I think with one to many or many to many that this isn't possible as it breaks the immutability of types generated by autovalue.

**Comment by Squeazer** [comment]
I'm using Requery + AutoValue, and I've hacked my way into using relations. Basically what i wanted was to have all my classes that are used across the app be immutable and using AutoValue. So I used regular mutable classes for requery, which I then convert to AutoValue after reading from DB, and convert them to regular classes when writing them to the DB.

For example, my AutoValue class:
```java
@AutoValue
public abstract class Session {

    public abstract String id();
    
    public abstract List<DeviceData> deviceData();

    public abstract long timestamp();

    public static Builder builder() {
        return new AutoValue_Session.Builder();
    }

    @AutoValue.Builder
    public abstract static class Builder {

        public abstract Builder setDeviceData(List<DeviceData> deviceData);

        public abstract Builder setId(String id);
        
        public abstract Builder setTimestamp(long timestamp);

        public abstract Subsession build();
    }
}
```

And my Entity class:
```java
@Table(name = "Session")
@Entity
public class SessionSM implements Persistable {

    @Key
    String id;

    @OneToMany
    List<DeviceDataSM> deviceData;
    
    long timestamp;
    
    public Session toAutoValue() {
        return Session.builder()
                .setId(id)
                .setDeviceData(SMUtils.convertDeviceData(deviceData))
                .setTimestamp(timestamp)
                .build();
    }

    public static SubsessionSM toEntity(Subsession session) {
        SubsessionSMEntity entity = new SubsessionSM2Entity();
        entity.setId(subsession.id());
        entity.setTimestamp(subsession.timestamp());
        entity.getDeviceData().addAll(SMUtils.convertDeviceDataSM(session.deviceData(), entity));
        return entity;
    }
}
```

Then when reading from the DB:
```java
public Observable<List<Session>> getSessions() {
    return entityStore.select(SessionSM.class).get().observable()
            .map(SessionSM::toAutoValue)
            .buffer(20);
}
```

And writing to the DB:
```java
public Completable setSubsessions(List<Subsession> sessions) {
    List<SessionSM> sessionSMEntities = new ArrayList<>();
    for (Session session : sessions) {
        sessionSMEntities.add(SessionSM.toEntity(session));
    }
    return entityStore.upsert(sessionSMEntities).toCompletable();
}
```

Still not sure why this isn't possible directly with Requery. It's not like it would be impossible to do... you could just read the values from the DB when instantiating the AutoValue object, instead of reading them on-demand, right? Not the best thing for performance, but it would get the job done. 
And if you really wanted on-demand loading, you could implement it, the List's inside of AutoValue classes can still be changed since they themselves aren't immutable (but that really defeats the purpose of an immutable structure, so preloading the data would probably be better).

IMO, not having this supported is a real drawback, since you can't really have any nesting in your entities, you can only use primitive types...

**Comment by npurushe** [comment]
This is somewhat related to eager fetching. The reason this isn't supported is that while it would work ok in your example, in many other cases those eagerly loaded objects may also have relations as well. In which case you end up possibly having to load an extremely large number of objects just from loading one. 

I am looking at ways to improve the usage of immutable types with relations. One possible feature would detach the relations from the entity object and put them on something like a generated repository class and allow you to load them separately. You can do this now just using the query API but this would reduce boilerplate around that.
