### ISSUE TITLE
Kotlin interface default methods are not accessible

### ISSUE THREAD

**Issue by consp1racy** [requery/requery#264]
Code

    var roles: String?

    @Transient
    fun getRolesAsSet(): Set<String> = this.roles?.split("|")?.toSet() ?: emptySet()

    fun setRolesAsSet(roles: Set<String>) {
        this.roles = roles.joinToString("|")
    }

results in

    private Set<String> rolesAsSet;

plus a getter and setter. Similarly if a property with custom getter/setter is used.

The empty setter and getter hides the original methods.

**Comment by npurushe** [comment]
Unfortunately these are not generated as Java 8 default methods (https://youtrack.jetbrains.com/issue/KT-4779), so any Java code implementing them must implement the method in some way to compile. Regardless this is something that can only work in Java 8. Alternatively you can add it as a extension method which should work fine.

**Comment by consp1racy** [comment]
Yes, extension methods produce desired result. Thanks for the tip.

**Comment by consp1racy** [comment]
It's ok in sense that Kotlin produces Java 6 bytecode. So the methods are generated and accessible for any class implementing said interface.

I think the issue is requery processor eagerly treats these methods as entity properties and emits overriding methods. If these methods were not generated, Kotlin default methods from the interface would remain accessible.

**Comment by npurushe** [comment]
The problem is these methods have to be overridden in any java class implementing the interface  otherwise they won't compile. It can only work if 
a) Kotlin source code is generated instead which is not supported by kapt yet
b) Java 8 compatible source and bytecode is used and used with a Kotlin version with https://youtrack.jetbrains.com/issue/KT-4779. requery will not override Java 8 default methods in the next version
