### ISSUE TITLE
Using Abstract class doesn't generate setter for list relations

### ISSUE THREAD

**Issue by aegis123** [requery/requery#268]
I'm using the interface entity now and was trying out it out as abstract class entity but when I changed it. The generated code didn't have a setter for `@OnToMany` and `@ManyToMany` attributes with a `List`/`Set` type I also tried it with `Result`/`MutableResult` which also doesn't generate the setter. The getter are generated correctly though.

Also `@OneToOne` generates correctly both a setter and getter when using an Abstract class entity

**Comment by npurushe** [comment]
This is intentional. Changes to collections must be tracked internally by requery, so they are created automatically, and you simply add/remove items from the collection. Allowing the collection to be replaced is error prone and usually not what users intend. Instead use the standard collection api to modify it (add/remove/clear/addAll etc)

**Comment by aegis123** [comment]
Okay that I can understand. @npurushe does that also mean that if it can't find any relationships (empty table for instance) that it will have an empty list in which you can add new entities? Also why does the interface Entity generate the setter then shouldn't it also only generate a getter?

**Comment by npurushe** [comment]
Yes it will have a default collection in which you can add entities. I agree the interface should probably not generate a setter unless it is required for some reason.
