### ISSUE TITLE
Question about delete operation

### ISSUE THREAD

**Issue by oleonov** [requery/requery#29]
Hi!
I move my project from activeandroid to requery and have some question.
For example, how can I do opeartion with blocking thread.
`MyApplication.getInstance().getData().toBlocking().*`?

Why this code not working?
```java
MyApplication.getInstance().getData().toBlocking().delete(City.class).get();
List<City> wasCities=MyApplication.getInstance().getData().select(City.class).get().toList();
MyApplication.getInstance().getData().toBlocking().insert(cities);
```

`wasCities` contains items after deletion.

**Comment by npurushe** [comment]
Hi. The issue here is delete().get() just creates the operation of type `Scalar<Integer>` that has to evaluated. You can evaluate it by calling `value()` or `consume(Consumer<? super E> action)`. Something like:

```java
Integer rowsDeleted = MyApplication.getInstance().getData().toBlocking().delete(City.class).get().value();
List<City> wasCities=MyApplication.getInstance().getData().select(City.class).get().toList(); // will be empty now
```

Will make this more clear in the examples and documentation. Sorry about any confusion. Thanks for reporting!

**Comment by oleonov** [comment]
Thanks! Looks complicated)

**Comment by npurushe** [comment]
The reason for that is that API is designed to be fully non-blocking/reactive. I agree its a little bit more complicated in blocking use cases, there will be some improvements there

**Comment by oleonov** [comment]
I know, but using retrofit+rxAndroid I need blocking operation inside `onNext`. How can I do it simpler?
```
NetworkApi.getServerApi().getCities()
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(new Observer<List<City>>() {
                    @Override
                    public void onCompleted() {
                        sendBroadcast(new Intent(BroadcastHelper.ACTION_CITY_LOADED));
                        System.out.println("onCompleted");
                    }

                    @Override
                    public void onError(Throwable e)
                    {
                        ...
                    }

                    @Override
                    public void onNext(List<City> cities) {
                        System.out.printf("onNext %s\n", cities);
                        if(cities!=null)
                        {
                            MyApplication.getInstance().getData().toBlocking().delete(City.class).get().value();
                            MyApplication.getInstance().getData().toBlocking().insert(cities);
                        }
                    }
                });
```

**Comment by npurushe** [comment]
I'm not sure that's what you want because then you are doing the database operations on the main thread then. You probably want to use the rx [map()](http://reactivex.io/documentation/operators/map.html) operator to apply functions to the observable which can do the database work before the final subscription.

**Comment by oleonov** [comment]
Thank you! I did so and get more speed for UI.
