### ISSUE TITLE
Entity classes can only be placed in $APP_PACKAGE_NAME/model

### ISSUE THREAD

**Issue by noberasco** [requery/requery#300]
Subject says it all: if I try to put Entity classes under any other package name, compilation will fail because the generated classes will not be able to locate the Entity classes

**Comment by aegis123** [comment]
Do you recompile the project after moving? since new Entity classes should be generated again in the same package your Abstract/Interface Entities are.

**Comment by consp1racy** [comment]
Wherever you use your entity in variables use the original type e.g. `IEntity` or `AbstractEntity`. The import statements will be updated by your IDE when you move these classes.

You'll have to update import statements manually wherever you reference generated `Entity` class.

**Comment by noberasco** [comment]
Actually, my problem is not that my code cannot find the non-abstract Entity classes.
The problem is that the non abstract Entity classes fail to compile.

Here follow some more details...

This is the package where I would like to put my abstract Entities to:
![shot1](https://cloud.githubusercontent.com/assets/475725/19385767/d49fe61a-9210-11e6-8d5d-543d0ab1e8b1.png)

This is the actual implementation of the abstract Entity:

    @Entity
    public abstract class AbstractCachedTile {

        @Column(nullable = false, name = "tile_hash")
        long tileHash;

        @Column(nullable = false, length = 25, name = "cache_key")
        String cacheKey;

        @Column(nullable = false, name = "last_used")
        double lastUsed;

        @Column(nullable = false, name = "data")
        byte[] data;
    }

When I attempt to compile the project so configured, the compilation of the non-abstract CachedTile class fails:
![shot2](https://cloud.githubusercontent.com/assets/475725/19386014/3ce4ce38-9212-11e6-8fd8-5f46926ec1ec.png)

If I go see the generated class, this is what I find:
![shot3](https://cloud.githubusercontent.com/assets/475725/19385967/0c4cf32c-9212-11e6-971a-71a18f4d24ac.png)

**Comment by aegis123** [comment]
first start by changing the package names to all lowercases so Core.DataModel.CachedTile should be core.datamodel.CachedTile and also instead of just using core.datamodel.CachedTile the package name should include the fully qualified name so com.zirak.easytrails.core.datamodel.CachedTile. Maybe check the class CachedTile if the package at the top of the file is correctly set to com.zirak.easytrails.core.datamodel; and not Core.DataModel;

**Comment by noberasco** [comment]
setting package names to all lowercase does indeed fix the compilation problem. After that the generated classes work just fine...

I do think, however, that package names with upper case letters ought to be supported. If I remember correctly, the convention of using all lowercase letters only applies to the top level domain prefix of the package name...

**Comment by aegis123** [comment]
The convention for using only lower case for package names is so you cant clash with classnames which start with uppercase.

Any java programmer would read `Core.DataModel.CachedTile` as class `Core` has an inner class `DataModel` which has an inner class `CachedTile` instead of the the class `CachedTile in the package `core.datamodel`.

**Comment by noberasco** [comment]
I see.
If that is the case then this issue can be closed.

Do you by chance have any feedback for issue #252? That one is rather more serious...
