### ISSUE TITLE
Feature request: Parameterless copy function on generated entities

### ISSUE THREAD

**Issue by consp1racy** [requery/requery#343]

**Comment by npurushe** [comment]
What would you expect it to do shallow vs deep copy? both have various issues

**Comment by consp1racy** [comment]
Shallow seems the only reasonable option since fields on entities are not guaranteed to have implemented a deep copy mechanism. Kotlin data class copy function does the same. Primitives and strings by val, objects by ref.

**Comment by consp1racy** [comment]
Intent:
Make copy function accessible from the interface via defining `fun copy(): E`.

Current behavior:
Defining the copy function on the interface (`fun copy(): E`) rather creates a property named `copy`. 

Expected behavior:
 - Throw exception on conflict.
 - Disable property named `copy` altogether
 - Require copy function on the interface when `copyable = true`.
 - ...

**Comment by consp1racy** [comment]
What's the behavior when `cacheable = true`?

Will the produced entity be detached from Requery (as unmanaged objects from Realm)?

**Comment by npurushe** [comment]
You can still define the copy function in an interface (e.g. `Copyable`) and have the class implement it. Need to avoid having magic method names excluded since they can clash with valid column names and have other side effects. It might be possible to come up with a exclusion here that works will look into it.

Cacheable means the `EntityCache` will be used for the entity, by default this means keeping weak references to any entities created.

**Comment by consp1racy** [comment]
Meaning the copy is not reachable via a query to the store. That's what I need. Thank you for the explanation.
