### ISSUE TITLE
which part requires android-15?

### ISSUE THREAD

**Issue by NeilCannon** [requery/requery#351]
Is it a specific dependency like sqlcipher, or more extensive?

**Comment by consp1racy** [comment]
Thoughts:
- Gingerbread (API 9-10) is six years old and only 1.3% of users worldwide have it.
- Virtually nobody has Android 3 (API 11-13).
- Virtually nobody uses API 14, Android 4.0.0-4.0.2 (it was quickly replaced by API 15, Android 4.0.3-4.0.4).
- It's a major pain in the ass to support anything below API 14 (API 17 if you work with Android UI).

Source:
https://developer.android.com/about/dashboards/index.html
http://android-developers.blogspot.cz/2016/11/google-play-services-and-firebase-for-android-will-support-api-level-14-at-minimum.html

AFAICS it was a design choice. Let's wait for an official statement.

Would you like lower minSdkVersion? If so, why?

**Comment by NeilCannon** [comment]
Yes, it's very rare to support anything lower than 15 :)
But currently I *have to* support 7, so I'm curious which pieces of this lib actually need >7

**Comment by npurushe** [comment]
@consp1racy makes some good points. There are a number of api's such as `android.database.Cursor.getType` and 
`android.database.sqlite.SQLiteStatement.executeUpdateDelete` that are required and don't exist at that API level. Most of these are added in API level 11 (honeycomb) however since most supported honeycomb devices received at least ICS MR1 (API 15) it makes sense to make that the min required version.
