### ISSUE TITLE
In Android Example the io.requery.android.example.app.model.Models class is missing

### ISSUE THREAD

**Issue by martijndebruijn** [requery/requery#36]
When I import the projects into Android Studio the Android example complains that the io.requery.android.example.app.model.Models is missing.

**Comment by npurushe** [comment]
Try building from the gradle command line are there any errors? Also I wouldn't recommend importing the whole requery project into Android Studio because Android Studio's support for regular java projects is pretty limited for some reason, instead just import the example project only and change the dependencies of the example to the maven ones list on the README.md (first page of the project).

**Comment by AllenVork** [comment]
when i compile the sample i got a warning "Error:(40, 12) : 2 mappings found for: io.requery.android.example.app.model.PhoneEntity.owner -> io.requery.android.example.app.model.PersonEntity"
