### ISSUE TITLE
Question on updating relationships.

### ISSUE THREAD

**Issue by Glurt** [requery/requery#379]
I have an Account entity that has a ManyToMany relationship with a Subscription, an Account has many Subscriptions. a Subscription can be subscribed to by many Accounts, you get the idea.

What I'd like to do is refresh an Accounts Subscriptions from the server and update the Account in the database, currently I'm trying to do this by just clearing the Accounts Subscriptions, adding the new list from the server and then upserting the Account. I'm not entirely sure what's happening but at some point the refreshAssociations method is triggered and the result of the queryInitializer is 0, which means that the Account no longer has any Subscriptions. The Subscriptions are still in the database however. 

Similar to this, I'd like to be able to automatically remove Subscriptions that no longer have any subscribed Accounts, is this something that happens already if the relationship becomes empty?

**Comment by npurushe** [comment]
Most likely you will need to something like this in a transaction:, it's important to retrieve any existing account with a given key first, instead of creating each time, as requery can't know the references unless the entity has been fetched or persisted.

```java
Account account = findByKey(Account.class, <key>);
if (account != null) {
    account.getSubscriptions().addAll(<subscriptions>);
    store.update(account);
} else {
// create new account
}
```

Making sure you are clearing any removed subscriptions first, before adding new ones. And also preferably mapping Subscriptions as a `java.util.Set`

Since the relation ship is many to many you'll have to delete all the subscriptions that have no accounts associated with them. This could only probably only be done automatically through a custom trigger, otherwise you can implement it easily in your application code.
