### ISSUE TITLE
OneToOne(mappedBy="") column is null

### ISSUE THREAD

**Issue by AlexeyKorshun** [requery/requery#409]
Good day.
I try your lib, and when I create 2 entities with one to one relationship nested model have null field which marked as @OneToOne(mappedBy="") 
my model: 
```
    @Key
    int id;

    @JsonProperty("head_coach")
    @ForeignKey
    @OneToOne
    HeadCoach coach;

    String name;
```
```
    @Key
    @Column(unique = true)
    String name;
    String photo;

    @OneToOne(mappedBy = "coach")
    Team team;
```

After insert my data to tables, I try to select all coaches, but all of them have team = null.

**Comment by npurushe** [comment]
Can you share what api calls you're making to insert them? Something like this:

```java
     Teat team = new Team();
...
     Coach coach = new Coach();
...
        team.setCoach(team);
        data.insert(team);
```

**Comment by AlexeyKorshun** [comment]
I fetch data from net, and parse it via jackson in Retrofit, but I try create data manuals, and had same effect : 

```
    HeadCoach coach = new HeadCoach();
    coach.setName("Coach");
    coach.setPhoto("photo");

    Team team = new Team();
    team.setId(10);
    team.setName("Avangard");
    team.setCoach(coach);

    data.upsert(team).subscribe();
```

**Comment by AlexeyKorshun** [comment]
In addition, in db all teams have null in coach column

**Comment by AlexeyKorshun** [comment]
Did you have answers?

**Comment by Agraphie** [comment]
I have tried your example and one side always gets inserted (depending where you put the `@ForeignKey` annotation), but not the other. Is this possibly a bug in bidirectional one-to-one mapping? So only one side gets inserted i.e. mapped but not the other? If you don't need the bidirectional mapping, as workaround I would propose to just remove one `@OneToOne` mapping. 

For me all teams don't have `null` in the coach column, but if you query the coaches, they won't have teams. Are you sure that all teams have `null` for coaches and all coaches return `null` for teams?

Furthermore, if you look at the generated SQL, the query is `select name, photo from HeadCoach` for getting all coaches while it should (probably?) be a join here in order to get the team for a coach. But as it's only a select, the `team` field has to be `null` for every coach.

**Comment by AlexeyKorshun** [comment]
@Agraphie oh sorry, it's my bad, teams have coach. But why selected coaches don't have team?
 It is important feature
