### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by miomao656** [requery/requery#43]
Is there a way to see what exact sql statements are generated by the library?

We have 10 tables in db with lots of relations between them (One to many, many to many, one to one) and we get a deep nested json mapped to response object from server that needs to be inserted in at least 8 tables,  we check every element by selecting and depending on if it exists doing insert or update.
For a response of 100 json objects (about 56kb) on xperia e it takes about 9 seconds to insert them with lots of gcforaloc calls, galaxy s4 takes about 2.3 seconds.

Could you give an example for a rule of thumb how this should be done?

**Comment by npurushe** [comment]
Hi yes you can add `setLoggingEnabled` on `DatabaseSource` and the statements will be logged under the tag `requery`. Be sure to put your code block that's doing those operations in a transaction via `runInTransaction` [link](http://requery.github.io/javadoc/io/requery/sql/EntityDataStore.html#runInTransaction-java.util.concurrent.Callable-) that's most likely the cause of your slowdown if you are inserting lots of objects.

**Comment by miomao656** [comment]
Hi,

Yes i found setLoggingEnabled, and put the whole interting method in runInTransaction and it shaved off 2 seconds on xperia and 1 second on s4

**Comment by npurushe** [comment]
Some other suggestions, since don't know your exact steps. For checking if something exists you can just query for the id instead of the whole object, you can also use the limit clause to filter your results to just 1 object. Also if you are iterating through object links to check for something it may be possible to convert that into a query that is less work.
