### ISSUE TITLE
@OneToMany in kotlin

### ISSUE THREAD

**Issue by tonyjs** [requery/requery#438]
define entity Test
```
@Entity
interface Test {
    ...
    @get:OneToMany
    var aList: MutableList<A>

    @Entity
    interface B : A, Persistable, Parcelable {
        ...
    }

    @Superclass
    interface A  {
        @get:Key
        @get:Generated
        val id: Long

        @get:ManyToOne
        val test: Test

        @get:Column(value = "empty")
        val type: String
    }
```

compile... and then get error
 > Error:(35, 8) error: Test is not abstract and does not override abstract method setAList(List<A>) in Test
> Error:(365, 17) error: name clash: setAList(List<? extends A>) in Test and setAList(List<A>) in Test have the same erasure, yet neither overrides the other

hmm... I think that it has relavance with Kotlin's Generic type. right?

Can you tell me the reason why and how can I solve this, please?

**Comment by npurushe** [comment]
Hi you can solve this by making `var aList` `val aList` instead. The reason for this is the generated implementation will contain an initialized collection, that should be modified via clear/add/remove rather than overwriting the collection, this makes change tracking the collection easier and less error prone.

Hope that makes sense thanks!
