### ISSUE TITLE
Declaring foreign keys with Immutables/AutoValue Builders.

### ISSUE THREAD

**Issue by autovalue** [requery/requery#441]
Slightly related to #128 but is there any working examples of how to work with ForeignKeys/JunctionTable/ManyToOne when using extensions like AutoValue/Immutables?

The main reason I initially went the AutoValue route was its its builder pattern, [normalization](https://github.com/google/auto/blob/master/value/userguide/builders-howto.md#normalize) support and ability to generate `Parcelable` methods .
But eventually found the main limitation of using AutoValue with this library was the inability to declare relational references giving me the dreaded: `Immutable value type cannot contain relational references` error.

I eventually found through your [android example](https://github.com/requery/requery/blob/a51d5c5014c9c310bbfd9864fa6596a05a779ab9/requery-android/example/src/main/java/io/requery/android/example/app/model/Phone.java) that you already supported `Parcelable` generations (hidden gems like this should definitely be included in the repo's README).

This already ticks one box off with me moving away from AutoValue for my Entity. The only features left are builder support for non-immutable entities + normalization.

It would be nice if we had builder support for non-immutable entities (either provided by the user, or generated from annotation processing) - preferably user-generated with the ability to extend an existing builder (so we can normalize it ourselves).

**Comment by autovalue** [comment]
For the meantime until better support for this feature is available, I've decided to move away from AutoValue, and will instead be using a simple class, but with a manually generated builder using any of the following IntelliJ plugins:
https://plugins.jetbrains.com/idea/plugin/7354-innerbuilder
https://plugins.jetbrains.com/idea/plugin/8276-stepbuilder-generator

It's not the best as it doesn't generate the strict nullability checks AutoValue does at runtime which reduces the potential bugs, but it is manageable for the time being.

**Comment by npurushe** [comment]
When using immutable types you define foreign key information [example](https://github.com/requery/requery/blob/master/requery-test/src/main/java/io/requery/test/autovalue/Phone.java), as part the entity definition, Junction tables need to be defined as part of the model they can't be inferred. 

There is a trade off between immutable vs mutable types. For some an immutable type that maps directly onto a row is all they are looking for. With the understanding that things like lazy loading and relationship collections won't be possible because they violate immutability. For others POJO type objects with getter/setters and relationship collections is better. 

For parcelable support this also has some limitations, if your intentions are to pass data inside your own Android app process then you should actually avoid parcelables and instead pass entity keys and then use findByKey to retrieve them. This ensures you actually get back the original entity in it's original state, by default these objects are cached in memory.

**Comment by autovalue** [comment]
> When using immutable types you define foreign key information example, as part the entity definition, 

Now I remember why I glossed over that example. It uses `@javax.persistence.JoinColumn`, but I am using an SQLite database on Android, so I assummed [that](https://mvnrepository.com/artifact/org.eclipse.persistence/javax.persistence/2.1.1) annotation wasn't supported, can you confirm whether it would've worked with it?

For others who might need this, I was able to generate the foreign key schema through:
```java
@Key
@ForeignKey(referencedColumn = "_id", references = Parent.class)
@Column(name = "foreign_id", nullable = false)
public abstract int foreignId();
```

**Comment by npurushe** [comment]
Right that particular test was using jpa annotations just substitute with the equivalent requery annotations. Requery supports both, but there are not tests/examples for all possible combinations of everything just yet.

**Comment by autovalue** [comment]
Cool thanks for all the help.
