### ISSUE TITLE
Add sample project

### ISSUE THREAD

**Issue by hotchemi** [requery/requery#45]
Do you have any plan to add sample project which shows sample usage?

**Comment by npurushe** [comment]
For android there is a sample project here https://github.com/requery/requery/tree/master/requery-android/example. For java the test code is the sample for now, but planning to add better samples there. Any specific usage you want to have documented?

**Comment by Pr0bability** [comment]
Honestly, I am at a total loss on how the DSL query are supposed to work. The Javadoc is of no help whatsoever. Any chance on something with this? For example, suppose I have an Entity Worker with a One-To-Many relationship to another Entity Pay. Now, I want to query for the last instances of Pay by their date (a long timestamp). How would I go about doing that?

**Comment by npurushe** [comment]
I have added a set of example queries in the [wiki](https://github.com/requery/requery/wiki/Query-examples). For your case because you are quering a foreign key reference that is currently not exposed as a queryable attribute. That should have been documented but it was in progress and the change is now committed https://github.com/requery/requery/commit/92a4fa238610b61e86a91f35505e63f9519bce22. With the change it would be something like:

`data.select(Pay.class).where(Pay.WORKER.eq(worker)).orderBy(Pay.DATE.desc()).get()`

If you have any questions let me know
