### ISSUE TITLE
Primitive arrays - java.lang.String cannot be cast to [F

### ISSUE THREAD

**Issue by MrOnyszko** [requery/requery#454]
Hi, how to store primitive arrays? When I try to upsert an entity that contains float array I get following exception "java.lang.String cannot be cast to [F". I don't understand that. Am I missing something?

This is my entity:
```java
@Entity
public abstract class Shape {

    @Key
    @Generated
    int id;

    float[] points;

}
```

**Comment by npurushe** [comment]
Most databases don't support storing arrays as columns. Some do however and this something requery will support soon. Which database are you using?

For those that don't you could store them as a comma separated string for example. You can define a `Converter` to do this for [example](https://github.com/requery/requery/blob/master/requery-test/src/main/java/io/requery/test/model/IntegerListConverter.java). However you should make sure your schema fits a relational model otherwise a database maynot be the best storage option. Hope that makes sense.

**Comment by MrOnyszko** [comment]
I'm using SQLite on Android with ReactiveEntityStore. `Converter` was helpful.

Thanks for your fast response and keep up your good work!
