### ISSUE TITLE
Read empty array --> ClassCastException: Cannot cast java.lang.String to java.util.List

### ISSUE THREAD

**Issue by FlorangOutang** [requery/requery#477]
Hello, 

I have an issue that I can't solve so far.
I'm not sure if I'm doing something wrong or if it's requery that doesn't understand what I'm trying to do...
Anyway, here is my problem : 
I am trying to read an empty array value that I've saved as an ArrayList in requery. 
The result is the following ClassCastException : 

<addr> **java.lang.ClassCastException: Cannot cast java.lang.String to java.util.List** <addr>
![capture d ecran 2017-03-21 a 11 56 15](https://cloud.githubusercontent.com/assets/5547520/24144807/f18db1b8-0e2e-11e7-8106-dda497d59feb.png)

The value that it is trying to cast to list is the following  : 
![capture d ecran 2017-03-21 a 11 54 49](https://cloud.githubusercontent.com/assets/5547520/24144783/d6032ee6-0e2e-11e7-9c23-372794e383fc.png)

I guess, this value is the result of an empty array return by the API like this : 
![capture d ecran 2017-03-21 a 11 56 44](https://cloud.githubusercontent.com/assets/5547520/24144844/0f7054f6-0e2f-11e7-9612-3a1d63b34272.png)
or like this : 
![capture d ecran 2017-03-21 a 11 56 34](https://cloud.githubusercontent.com/assets/5547520/24144859/21bad05a-0e2f-11e7-9dc6-2b7e147dac42.png)

I've strated using Requery just weeks ago.
Can you tell me if I am doing something wrong ?

Thnak you

**Comment by npurushe** [comment]
Arrays aren't generally a native column type in sqlite. You could store them as a comma separated string for example. You can define a `Converter` to do this for [example](https://github.com/requery/requery/blob/master/requery-test/src/main/java/io/requery/test/model/IntegerListConverter.java). 

However in general you should make sure your schema fits a relational model otherwise a database may not be the best storage option. e.g. `Authors` should probably be it's own table. Hope that makes sense.
