### ISSUE TITLE
Reinit database question

### ISSUE THREAD

**Issue by miomao656** [requery/requery#54]
We initialize datastore like this:

```
      DatabaseSource source = new DatabaseSource(context, Models.CDGENERAL, GENERAL_DB, 1);
      Configuration configuration = source.getConfiguration();
      generalDataStore = new EntityDataStore<>(configuration);
```

When we log out user from app, database is deleted and we call `generalDataStore.close() `

After new user logs in again we reinitialize EntityDataStore the same way as above and on first call generalDataStore.select we get this exception. 

```
io.requery.PersistenceException: closed
W:     at io.requery.sql.EntityDataStore.checkClosed(EntityDataStore.java:498)
W:     at io.requery.sql.EntityDataStore.select(EntityDataStore.java:387)
```

How to properly reinitialize datastore again in runtime?

**Comment by npurushe** [comment]
Hi, I think you may have a reference to the old store when you call select() because that exception is only thrown if close() was called on that particular instance of `EntityDataStore`. `DatabaseSource` holds onto the connection since there is only one connection in Android. I think you if you use something like the following it should be ok and after closing the database file will be unlocked:

Open:
```java
      source = new DatabaseSource(context, Models.CDGENERAL, GENERAL_DB, 1);
      Configuration configuration = source.getConfiguration();
      generalDataStore = new EntityDataStore<>(configuration);
```
Close:
```java
if (generalDataStore != null) {
    generalDataStore.close();
    generalDataStore = null;
}
if (source != null) {
    source.close();
    source = null;
}
```

This is similar to what is done in the Android test code, which closes and opens the database many times (for each test case).

**Comment by miomao656** [comment]
HI,
Tnx for the clarification, i will try and let you know :+1:

**Comment by miomao656** [comment]
Confirming this works, tnx!

**Comment by npurushe** [comment]
Great!
