### ISSUE TITLE
How does requery handle entity changes on version increment.

### ISSUE THREAD

**Issue by andre-artus** [requery/requery#551]
I've been searching in the issues and in general for the correct way to handle changes to my entity model. Up to now I've had the luxury of just deleting the old DB, but this is no longer the case..

I know of the `version` parameter when constructing `DatabaseSource`, but how does `requery` know which columns/fields/properties belong to which version. I've found a @Version annotation, but its unrelated to this. Will the versioning be messed up if I delete generated code?

I take it requery does not drop columns, if you have an old required column, but it's no longer used can the upgrade modify it to use a default value, or change to nullable?

I'm using the following:
Android 
requery 1.3.
Kotlin 1.1.2-3
KotlinEntityDataStore.
TableCreationMode.DROP_CREATE

Thank you

**Comment by npurushe** [comment]
requery supports additive changes to a database model. That is you can add tables/columns/indexes and it will generate the sql to create them when you update the model schema version. It does this by querying the existing columns and adding the missing ones.

Dropping columns/indexes or changing the fundamental type of a column are a more complex case because existing data will have to be lost, possibly in unpredictable ways. For your specific case about removing a non-null constraint, that's not really supported in SQLite you would have to move the data into a new table without the constraint.

**Comment by andre-artus** [comment]
Thanks,
Is there a way to hook into requery's upgrade function to run my own SQL?

**Comment by npurushe** [comment]
Hi yes you can extend `DatabaseSource` which extends Android's builtin `SQLiteOpenHelper` then you can override `onUpgrade` to execute any custom statements you need.

**Comment by andre-artus** [comment]
Thanks again. Much help
