### ISSUE TITLE
Many entities on the same table

### ISSUE THREAD

**Issue by rowysock** [requery/requery#567]
Due to limitation of immutable types, which cannot contain relational links, I would like to have two version of the same entity. One with immutable foreign key, and the second, mutable with relational link. 

Idea here is to insert into DB many entities linked with foreign keys, and later retrieve all of them with one query, using relational annotations

Is it possible?

I tried using @Table with the same name on both entities but it fails while creating schema. I also tried to set the same entity name but it fails during code generation.

Anyway why isn't is possible to have relational links on immutable types with eager fetch?

**Comment by npurushe** [comment]
Having two versions would cause a number of problems. Having a traditional mutable java object is not necessarily wrong if used correctly. The reason why eager fetch isn't supported with immutable objects is it can cause a large amount of queries to be made due to back references. 

If you need relational links then mutable java objects is the best way to achieve that. Some users only require plain row mapping to a table, in which immutable objects fit that use case, in which relations can be resolved separately through the query api. These two strategies however can't really be combined. Hope that makes sense.
