### ISSUE TITLE
@Embedded kotlin fails to compile

### ISSUE THREAD

**Issue by gmribas** [requery/requery#588]
```
@Entity
interface Person : Parcelable, Persistable {
    @get:Key
    @get:Generated
    val id: Int

    var name: String

    ...

    @get:Embedded
    var picture: Picture
}
```

```
@Embedded
interface Picture : Parcelable, Persistable {

    var thumbnail: String?

    var original: String?
}
```

The result is

> FAILURE: Build failed with an exception.
> 
> What went wrong:
> Execution failed for task ':requery-android:example-kotlin:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

![selection_001](https://user-images.githubusercontent.com/2753221/27146953-7b1fcebe-5111-11e7-94f3-8e3b5d44229b.png)

Java version works fine.

```
@Entity
public interface Person extends Observable, Parcelable, Persistable {

    @Key @Generated
    int getId();

    @Bindable
    String getName();

    ...

    @Embedded
    Picture getPicture();
}
```

```
@Embedded
public interface Picture {

    @Nullable
    String getOriginal();

    void setOriginal(String original);

    @Nullable
    String getThumbnail();

    void setThumbnail(String thumbnail);
}
```

**Comment by npurushe** [comment]
In this case the actual error is `Error:(32, 7) Gradle: error: PersonEntity is not abstract and does not override abstract method setPicture(Picture) in Person`

This is because 'picture' was declared as `var` it should be declared as `val`, to fix the compilation. The reason setters aren't generated for embedded types is that it prevents common mistakes of overwriting all the embedded value fields.

**Comment by gmribas** [comment]
Thanks

**Comment by gmribas** [comment]
@npurushe I've changed it to `val` and still doesn't work.

```
@get:Embedded
val picture: Picture
```
[stacktrace.txt](https://github.com/requery/requery/files/1085741/stacktrace.txt)
