### ISSUE TITLE
unidirectional many-to-one relation

### ISSUE THREAD

**Issue by anatoly-kryzhanovsky** [requery/requery#599]
Hi there

i have following sample entities:
```
@io.requery.Entity
public interface Parent {
    @Key
    @Generated
    int getId();
    void setId(int value);

    @OneToMany
    Set<Child> getChilds();
}
```

```
@io.requery.Entity
public interface Child {
    @Key
    @Generated
    int getId();
    void setId(int value);

    @Column
    String getName();
    void setName(String value);
}
```

so, each parent have many children, but child does not have back reference to it parent (in my case i cannot add this link: i cant modify structure of entity)
so, then i compile my solution (android app) i have following message:
error: Corresponding @OneToMany relation not present in mapped entity

is requery support unidirectional relation? 

update:
i try to set mappedBy attribute in onetomany mapping:
`@OneToMany(mappedBy = "id")`

but now i receive ParentEntity cannot be cast to java.lang.Integer error in runtime then try to save data

**Comment by npurushe** [comment]
You can make this work without a object back reference, however your `Child` type must have a key back to the Parent in order for the relation to work, otherwise relationally there is no where to store this information. `@OneToMany(mappedBy = "id")` doesn't make sense because the Child.id is not the same as the Parent.Id. Hope that makes sense.
