### ISSUE TITLE
Allow to use requery-jackson without EntityStore

### ISSUE THREAD

**Issue by rowysock** [requery/requery#606]
In my application I need to deserialize entity using Jackson way before i can initialize EntityDataStore. I want to use EntityMapper without passing EntityStore. If I'm not wrong EntityStore is used only for auto-generating of ids, which is not necessary in my case. 

Also mixing JSON parsing with Database access seems like mixing of concerns to me. It should be possible to perform those independently. 

Simple solution could be to make constructor of RequeryModule public, so it can be used without EntityMapper

**Comment by npurushe** [comment]
EntityStore is used to resolve existing objects by their keys (auto generated or otherwise). The purpose of the module is to provide this functionality so from that perspective it's not really mixing concerns. You can also initialize the store when your application is created, (that is how it's intended to be used)
