### ISSUE TITLE
Is Blob/Text supported (MySQL)?

### ISSUE THREAD

**Issue by NekoiNemo** [requery/requery#608]
I can't find an annotation to make my column a Blob/Text? Is it supported? If so - how can i make a column like that?

**Comment by npurushe** [comment]
Hi you can use a `java.sql.Blob` type directly inside an entity and it will be deserialized from a result/query correctly. But in order to create one (for an insert) you do have to use the JDBC Connection api directly, this is something that can be improved. For text this requires a custom [Column.definition](http://requery.github.io/javadoc/io/requery/Column.html#definition--) to set the type as text.

**Comment by NekoiNemo** [comment]
So i have to use separate update through JDBC to set the blob value?

**Comment by npurushe** [comment]
You just need the connection to create a Blob instance (see [Connection.createBlob](https://docs.oracle.com/javase/7/docs/api/java/sql/Connection.html#createBlob())). So for example if you a create new Entity it will have a null Blob, you can assign it a blob from the connection and then insert it. For an existing entity you queried from a select for example, the Blob instance would already be set and you can use it directly. There are some tricky database specific things with blobs so using smaller byte[] (varbinary) columns might be preferable instead.

**Comment by NekoiNemo** [comment]
Is there a way to access Connection instance from EntityDataStore? The simplest way i can find is to retain  somewhere the reference to the Configuration used to create it and obtain connection through configuration.connectionProvider?.connection which is a bit clunky.

**Comment by npurushe** [comment]
There wasn't an easy way to do this, but in the next release you would be able to extend `EntityDataStore` and then access `EntityContext` which the connection can be obtained from.
