### ISSUE TITLE
Using android-database-sqlcipher v4.0.1

### ISSUE THREAD

**Issue by mario** [requery/requery#858]
I have an app that used the previous 3.5.x version of android-database-sqlcipher and requery. When updating the dependency, the app crashes possibly because some migration steps are needed? But this is not mentioned anywhere.

**Comment by mario** [comment]
See this for details: https://discuss.zetetic.net/t/upgrading-to-sqlcipher-4/3283

I guess Requery needs a PR that would do such a migration automatically?

**Comment by npurushe** [comment]
These seems like a per application decision on how to upgrade, those pragmas mentioned in the article can be executed using the `DatabaseProvider` api requery provides, specifically `onUpgrade`

**Comment by xmkevinchen** [comment]
@npurushe 

According to the migration details, linked by @mario, the key to migration needs to be executed after opening the database immediately, with I'm not sure how to make sure this timing with `onUpgrade` method

```
override fun postKey(database: SQLiteDatabase?) {
    database?.rawExecSQL("PRAGMA cipher_migrate")
}
```

BTW,  I think `onUpgrade` severs the different purpose than this sqlcipher migration. The user might not modify his/her database in term of the schema. However, the user might just want to upgrade the sqlcipher to latest version due to some security needs.

**Comment by npurushe** [comment]
You can also use `onConfigure` or the SqlCipher api directly itself to do the migration.

**Comment by ArikYa** [comment]
FYI, I faced this issue as well, and the only way to set a hook to call `postKey` was using reflections. It will be beneficial if `SqlCipherDatabaseSource` will have a constructor that sets the hook
