### ISSUE TITLE
Problems with latest version of kotlin 

### ISSUE THREAD

**Issue by steelxtreme** [requery/requery#885]
Hello I'm getting :

Type mismatch. 
Required:
Condition<out Expression<TypeVariable(R)>, *>
Found:
Logical<out Expression<Serializable?>, Serializable?>

with  kotlin 1.3.41 version

**Comment by LukasForst** [comment]
This is because of the new inference algorithms used in the latest Kotlin releases - the code compiles but the Intellij shows the error. 

You can use the old algorithms that infer the Requery properly by disabling the new ones:

> Settings (`Ctrl` + `Alt` + `s`) -> Build, Execution and Deployment -> Compiler -> Kotlin Compiler -> disable Enable new type inference algorithms

However, this issue should be reported to JetBrains (if it is not reported already).
