### ISSUE TITLE
Kotlin data classes: not applicable to static or final member

### ISSUE THREAD

**Issue by PaulWoitaschek** [requery/requery#89]
When I have a simple data class like

```kotlin
@Entity data class Sample(val first: String)
```

The code does not longer compile with the warning:
>error: NotNull not applicable to static or final member
1 error

How to fix that?

Btw it took me some time to find this out. In addition requery should tell which class caused the problem and that it's requery throwing the exception.

**Comment by npurushe** [comment]
This error is emitted by the compiler not requery. It's because a Kotlin data class is final and it is not possible to extend it to add the state information. For now you should set @Entity(extendable = false) in your annotation so that the processor doesn't generate a class extending it. These types of entities will have the same restrictions as described [here](https://github.com/requery/requery/wiki/Immutable-types). But will update the processor to handle detecting this correctly.

**Comment by npurushe** [comment]
The beta15 version contains this fix
