### ISSUE TITLE
Is this library/project dead?

### ISSUE THREAD

**Issue by steelxt** [requery/requery#907]
Is this library/project dead?
due to Inactivity fixing bugs  for many months I'm wondering if this project will not be maintained.

**Comment by npurushe** [comment]
Hi no not dead, there are some long standing issues and enhancements that I still hope to make but they are more fundamental and require some re-thinking about the current architecture.

**Comment by decebals** [comment]
I try to [promote](https://www.reddit.com/r/java/comments/iv0oxe/jooq_vs_jdbi_vs_querydsl_vs_mybatis/g5or1nq/?utm_source=reddit&utm_medium=web2x&context=3) this library. I like it, the library is valuable (I use it in two personal projects), it's lightweight, but without a constant activity is very hard to gain adoption.
Do you have a roadmap for feature releases?

**Comment by noberasco** [comment]
+1
Latest commit is from March, 2020 which, considering the number of open issue, squarely puts the project into 'unmaintained' territory IMO.

**Comment by decebals** [comment]
> +1
> Latest commit is from March, 2020 which, considering the number of open issue, squarely puts the project into 'unmaintained' territory IMO.

The same conclusion. I'm sorry to see situation, because it's a good library and a lot of work was invested. I am an open source enthusiast with a lot of code published and I understand perfectly the situation. 
Sometimes, our priorities in life change and we do not have (enough) time to allocate to this kind of activity. It's a reality. 
In the end, I would like to thank @npurushe for the effort and patience!
